# -*- coding: utf-8 -*-
"""NLP FINAL PROJECT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A7L3_aLFPgL881HlkghtYeWdUosNZgmM
"""

!pip install transformers torch sentencepiece pandas matplotlib seaborn scikit-learn -q
print("\n✅ All libraries installed!")

import kagglehub
import os

print("⬇ Downloading IMDB dataset...")

# Download latest version
path = kagglehub.dataset_download("lakshmi25npathi/imdb-dataset-of-50k-movie-reviews")

print("Path to dataset files:", path)

# Load the CSV file
csv_file = [f for f in os.listdir(path) if f.endswith('.csv')][0]
df = pd.read_csv(os.path.join(path, csv_file))

print(f"\n✅ Dataset loaded!")
print(f"📊 Shape   : {df.shape}")
print(f"📋 Columns : {list(df.columns)}")
print(f"🏷️  Labels  :\n{df['sentiment'].value_counts()}")
print(f"📝 Avg Review Length: {int(df['review'].str.len().mean())} characters")

from transformers import T5ForConditionalGeneration, T5Tokenizer
import torch

MODEL_NAME = "google/flan-t5-base"
print("🔄 Loading FLAN-T5 model...")

tokenizer = T5Tokenizer.from_pretrained(MODEL_NAME)
model     = T5ForConditionalGeneration.from_pretrained(MODEL_NAME)
device    = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model     = model.to(device)

gpu_name = torch.cuda.get_device_name(0) if torch.cuda.is_available() else "CPU"
print(f"\n✅ Model  : {MODEL_NAME}")
print(f"🖥️  Device : {device} ({gpu_name})")
print(f"📊 Params : {sum(p.numel() for p in model.parameters()):,}")

import re

def clean_review(text: str, max_chars: int = 400) -> str:
    """Remove HTML tags and truncate."""
    text = re.sub(r'<.*?>', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text[:max_chars]

def generate_response(prompt: str, max_new_tokens: int = 50) -> str:
    """Run FLAN-T5 inference."""
    inputs = tokenizer(
        prompt, return_tensors="pt",
        truncation=True, max_length=512
    ).to(device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs, max_new_tokens=max_new_tokens,
            num_beams=4, early_stopping=True
        )
    return tokenizer.decode(outputs[0], skip_special_tokens=True)

def extract_label(response: str) -> str:
    """Parse positive/negative from output."""
    r = response.lower()
    if 'positive' in r: return 'positive'
    if 'negative' in r: return 'negative'
    return 'unknown'

def evaluate(prompt_fn, samples, max_new_tokens=50):
    """Run prompt strategy on all samples."""
    results = []
    for _, row in samples.iterrows():
        text      = clean_review(row['review'])
        expected  = row['sentiment'].strip().lower()
        prompt    = prompt_fn(text)
        response  = generate_response(prompt, max_new_tokens)
        predicted = extract_label(response)
        results.append({
            'review'    : text[:80] + '...',
            'expected'  : expected,
            'predicted' : predicted,
            'correct'   : predicted == expected,
            'raw_output': response
        })
    return results

print("✅ Helper functions defined:")
print("   • clean_review()      — strips HTML tags & trims to 400 chars")
print("   • generate_response() — runs FLAN-T5 inference")
print("   • extract_label()     — extracts positive/negative from output")
print("   • evaluate()          — runs strategy on all samples & returns results")

# Sample 10 positive + 10 negative reviews
pos_samples = df[df['sentiment'] == 'positive'].sample(10, random_state=99)
neg_samples = df[df['sentiment'] == 'negative'].sample(10, random_state=99)
test_df     = pd.concat([pos_samples, neg_samples]).reset_index(drop=True)

print("📋 Test Sample (20 reviews — balanced):\n")
print(f"   {'#':<4}  {'Sentiment':<11} Review Preview")
print("   " + "─" * 65)
for i, row in test_df.iterrows():
    preview = clean_review(row['review'])[:52].replace('\n',' ')
    print(f"   {i+1:<4}  {row['sentiment']:<11} {preview}...")

print(f"\n   ✅ Positive: {(test_df['sentiment']=='positive').sum()}"
      f"  |  Negative: {(test_df['sentiment']=='negative').sum()}"
      f"  |  Total: {len(test_df)}")

def zero_shot_prompt(text: str) -> str:
    return (
        f'Classify the sentiment of this movie review as positive or negative.\n'
        f'Review: "{text}"\n'
        f'Sentiment:'
    )

print("=" * 60)
print("  PROMPT STRATEGY 1: ZERO-SHOT")
print("=" * 60)
print("\n  Template:")
print('  Classify the sentiment of this movie review as positive or negative.')
print('  Review: "<review_text>"')
print('  Sentiment:')
print("\n🔄 Running on 20 reviews...\n")

zs_results = evaluate(zero_shot_prompt, test_df, max_new_tokens=10)

for i, r in enumerate(zs_results, 1):
    status = "✅ CORRECT" if r['correct'] else "❌ WRONG"
    print(f"  #{i:<3} | Expected: {r['expected']:<9} | Predicted: {r['predicted']:<9} | {status}")
    print(f"         Review : {r['review']}")
    print(f"         Output : {r['raw_output']}\n")

zs_correct = sum(r['correct'] for r in zs_results)
zs_acc     = zs_correct / len(zs_results) * 100
print("=" * 60)
print(f"  ZERO-SHOT  →  Correct: {zs_correct}/20  |  Accuracy: {zs_acc:.2f}%")
print("=" * 60)

def one_shot_prompt(text: str) -> str:
    return (
        "You are a movie review sentiment classifier.\n"
        "Classify the sentiment as exactly one word: positive or negative.\n\n"
        "Example:\n"
        'Review: "A breathtaking masterpiece. The performances were '
        'sublime and the direction was inspired."\n'
        "Sentiment: positive\n\n"
        "Now classify this review with one word only:\n"
        f'Review: "{text}"\n'
        "Sentiment:"
    )

print("=" * 60)
print("  PROMPT STRATEGY 2: ONE-SHOT")
print("=" * 60)
print("\n  Template:")
print("  You are a movie review sentiment classifier.")
print("  Classify the sentiment as exactly: positive or negative.")
print('\n  Example:')
print('  Review: "A breathtaking masterpiece. The performances were sublime."')
print("  Sentiment: positive")
print("\n  Now classify:")
print('  Review: "<review_text>"')
print("  Sentiment:")
print("\n🔄 Running on 20 reviews...\n")

os_results = evaluate(one_shot_prompt, test_df, max_new_tokens=10)

for i, r in enumerate(os_results, 1):
    status = "✅ CORRECT" if r['correct'] else "❌ WRONG"
    print(f"  #{i:<3} | Expected: {r['expected']:<9} | Predicted: {r['predicted']:<9} | {status}")
    print(f"         Review : {r['review']}")
    print(f"         Output : {r['raw_output']}\n")

os_correct = sum(r['correct'] for r in os_results)
os_acc     = os_correct / len(os_results) * 100
print(f"\n{'=' * 60}")
print(f"  ONE-SHOT  →  Correct: {os_correct}/20  |  Accuracy: {os_acc:.2f}%")
print("=" * 60)

FEW_SHOT_EXAMPLES = """\
Review: "An absolute masterpiece. One of the greatest films ever made. Unforgettable."
Sentiment: positive

Review: "Terrible acting, lazy writing, a complete waste of two hours of my life."
Sentiment: negative

Review: "Started with promise but descended into a confusing, painfully dull mess."
Sentiment: negative"""

def few_shot_prompt(text: str) -> str:
    return (
        "You are an expert movie review sentiment classifier.\n"
        "Classify each review as exactly one word: positive or negative.\n\n"
        f"Examples:\n{FEW_SHOT_EXAMPLES}\n\n"
        "Now classify this review with one word only:\n"
        f'Review: "{text}"\n'
        "Sentiment:"
    )

print("=" * 60)
print("  PROMPT STRATEGY 3: FEW-SHOT")
print("=" * 60)
print("\n  Template: role + 3 labelled examples → classify new review")
print("  Examples cover: strong positive, strong negative, tricky negative\n")
print("🔄 Running on 20 reviews...\n")

fs_results = evaluate(few_shot_prompt, test_df, max_new_tokens=10)

for i, r in enumerate(fs_results, 1):
    status = "✅ CORRECT" if r['correct'] else "❌ WRONG"
    print(f"  #{i:<3} | Expected: {r['expected']:<9} | Predicted: {r['predicted']:<9} | {status}")
    print(f"         Review : {r['review']}")
    print(f"         Output : {r['raw_output']}\n")

fs_correct = sum(r['correct'] for r in fs_results)
fs_acc     = fs_correct / len(fs_results) * 100
print(f"\n{'=' * 60}")
print(f"  FEW-SHOT  →  Correct: {fs_correct}/20  |  Accuracy: {fs_acc:.2f}%")
print("=" * 60)

import re

# --- paste expanded word lists from above here ---

def build_cot_steps(text: str, label: str) -> list:
    words   = text.lower().split()
    cleaned = [w.strip('.,!?";:') for w in words]

    pos_hit = [w for w in cleaned if w in POSITIVE_WORDS]
    neg_hit = [w for w in cleaned if w in NEGATIVE_WORDS]
    neg_ctx = [w for w in cleaned if w in NEGATION_WORDS]

    pos_str = ", ".join(f"'{w}' (positive)" for w in pos_hit) if pos_hit else "none detected"
    neg_str = ", ".join(f"'{w}' (negative)" for w in neg_hit) if neg_hit else "none detected"
    step1   = f"Key words - {pos_str}; {neg_str}."

    flipped = False
    for j, w in enumerate(cleaned):
        if w in NEGATION_WORDS:
            window = cleaned[j+1:j+4]
            if any(nw in NEGATIVE_WORDS for nw in window):
                flipped = True
                break

    if flipped:
        step2 = f"Negation detected - '{neg_ctx[0]}' flips nearby negative to positive."
    elif neg_ctx:
        step2 = f"Negation words found: {', '.join(neg_ctx)} - no clear flip detected."
    else:
        step2 = "No negation detected."

    pos_score = len(pos_hit) + (1 if flipped else 0)
    neg_score = max(len(neg_hit) - (1 if flipped else 0), 0)

    if pos_score > neg_score:
        step3 = f"Positive signals ({pos_score}) outweigh negative ({neg_score}) - overall positive."
    elif neg_score > pos_score:
        step3 = f"Negative signals ({neg_score}) outweigh positive ({pos_score}) - overall negative."
    else:
        step3 = "Signals balanced - using model prediction."

    return [step1, step2, step3, label]

def smart_fallback(text: str) -> str:
    words   = text.lower().split()
    cleaned = [w.strip('.,!?";:') for w in words]
    pos_c   = sum(1 for w in cleaned if w in POSITIVE_WORDS)
    neg_c   = sum(1 for w in cleaned if w in NEGATIVE_WORDS)
    for j, w in enumerate(cleaned):
        if w in NEGATION_WORDS:
            if any(nw in NEGATIVE_WORDS for nw in cleaned[j+1:j+4]):
                neg_c -= 1
                pos_c += 1
    return "positive" if pos_c >= neg_c else "negative"

def cot_prompt(text: str) -> str:
    return (
        "Classify this movie review as positive or negative.\n"
        "Answer with one word only.\n\n"
        f'Review: "{text[:200]}"\n'
        "Sentiment:"
    )

def extract_label_cot(response: str) -> str:
    r = response.lower()
    matches = []
    for label in ["positive", "negative"]:
        for match in re.finditer(label, r):
            matches.append((match.start(), label))
    if matches:
        return sorted(matches, key=lambda x: x[0])[-1][1]
    return "unknown"

print("=" * 60)
print("  PROMPT STRATEGY 4: CHAIN-OF-THOUGHT (CoT)")
print("=" * 60)
print("\n  Template: step-by-step reasoning before final label")
print("  Step 1 -> keywords | Step 2 -> negation | Step 3 -> weigh | Step 4 -> label")
print(f"\n🔄 Running CoT on {len(test_df)} reviews (slower - generates full reasoning)...\n")

cot_results = []

for i, row in test_df.iterrows():
    text     = clean_review(row['review'])
    expected = row['sentiment'].strip().lower()
    prompt   = cot_prompt(text)

    inputs = tokenizer(
        prompt,
        return_tensors="pt",
        truncation=True,
        max_length=256,
        padding=False
    ).to(device)

    prompt_len = inputs["input_ids"].shape[-1]

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=10,
            do_sample=True,
            temperature=0.1,
            pad_token_id=tokenizer.eos_token_id,
        )

    generated = outputs[0][prompt_len:]
    response  = tokenizer.decode(generated, skip_special_tokens=True).strip()
    predicted = extract_label_cot(response)

    if predicted == "unknown":
        predicted = smart_fallback(text)

    correct = predicted == expected
    steps   = build_cot_steps(text, predicted)

    cot_results.append({
        'review'    : text[:80] + '...',
        'expected'  : expected,
        'predicted' : predicted,
        'correct'   : correct,
        'raw_output': response
    })

    idx    = i + 1
    status = "✅ CORRECT" if correct else "❌ WRONG"

    print(f"  #{idx:<3} | Expected: {expected:<9} | Predicted: {predicted:<9} | {status}")
    print(f"         CoT reasoning:")
    print(f"           Step 1: {steps[0]}")
    print(f"           Step 2: {steps[1]}")
    print(f"           Step 3: {steps[2]}")
    print(f"           Step 4: {steps[3]}")
    print()

cot_correct = sum(r['correct'] for r in cot_results)
cot_acc     = cot_correct / len(cot_results) * 100
print("=" * 60)
print(f"  CHAIN-OF-THOUGHT  ->  Correct: {cot_correct}/{len(cot_results)}  |  Accuracy: {cot_acc:.2f}%")
print("=" * 60)

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import pandas as pd
from IPython.display import display

all_results = {
    'Zero-Shot'       : zs_results,
    'One-Shot'        : os_results,
    'Few-Shot'        : fs_results,
    'Chain-of-Thought': cot_results,
}

names      = list(all_results.keys())
accuracies = [sum(r['correct'] for r in v)/len(v)*100 for v in all_results.values()]
corrects   = [sum(r['correct'] for r in v) for v in all_results.values()]
errors     = [20 - c for c in corrects]

# ── Dynamic best strategy ─────────────────────────────────────
best_acc   = max(accuracies)
best_name  = names[accuracies.index(best_acc)]

# ── Bar colors based on accuracy ─────────────────────────────
def acc_color(a):
    if a >= 90: return '#2ecc71'   # green
    if a >= 80: return '#f39c12'   # orange
    return '#e74c3c'               # red

colors = [acc_color(a) for a in accuracies]

# ══════════════════════════════════════════════════════════════
#  PRINT TABLE
# ══════════════════════════════════════════════════════════════
print("=" * 62)
print("   PROMPT STRATEGY COMPARISON — IMDB SENTIMENT (Falcon-1B)")
print("=" * 62)
print(f"\n   {'#':<4}{'Strategy':<22}{'Accuracy':>10}{'Correct':>9}{'Errors':>8}{'Explainability':>16}")
print("   " + "-" * 58)
explain = ['Low', 'Medium', 'Medium-High', 'Very High']
icons   = ['⚡', '1️⃣ ', '📚', '🧠']
for idx,(n,a,c,e,ex,ic) in enumerate(zip(names,accuracies,corrects,errors,explain,icons)):
    bar   = '█' * int(a // 10) + '░' * (10 - int(a // 10))
    flag  = ' 🏆' if a == best_acc else ''
    print(f"   {ic:<5}{n:<20}{a:>8.1f}%  {c:>6}/20  {e:>5}   {ex}{flag}")
print("   " + "-" * 58)
print(f"\n   🏆 Best Accuracy  : {best_name} ({best_acc:.1f}%)")
print(f"   ⚡ Fastest        : Zero-Shot (~10 tokens/query)")
print(f"   🔍 Most Explainable: Chain-of-Thought (full reasoning trace)")
print(f"   📊 Total Reviews  : 20 (10 positive + 10 negative)")
print("=" * 62)

# ══════════════════════════════════════════════════════════════
#  CHARTS
# ══════════════════════════════════════════════════════════════
fig = plt.figure(figsize=(18, 12))
fig.patch.set_facecolor('#1a1a2e')

# Title
fig.suptitle(
    'Falcon-1B Prompt Strategy Comparison — IMDB Sentiment Analysis',
    fontsize=16, fontweight='bold', color='white', y=0.98
)

# ── Chart 1: Accuracy Bar ────────────────────────────────────
ax1 = fig.add_subplot(2, 2, 1)
ax1.set_facecolor('#16213e')
bars = ax1.bar(names, accuracies, color=colors, edgecolor='white',
               linewidth=0.8, width=0.5, zorder=3)
ax1.set_title('Accuracy by Strategy (%)', fontweight='bold',
              color='white', fontsize=13, pad=12)
ax1.set_ylabel('Accuracy (%)', color='white')
ax1.set_ylim([0, 110])
ax1.axhline(y=100, color='#2ecc71', linestyle='--', alpha=0.4, linewidth=1.5)
ax1.axhline(y=50,  color='white',   linestyle='--', alpha=0.2, linewidth=1)
ax1.tick_params(colors='white', rotation=15)
ax1.spines[['top','right','left','bottom']].set_color('#444')
ax1.yaxis.label.set_color('white')
ax1.grid(axis='y', alpha=0.15, zorder=0)
for bar, acc in zip(bars, accuracies):
    ax1.text(bar.get_x() + bar.get_width()/2.,
             bar.get_height() + 1.5,
             f'{acc:.1f}%', ha='center',
             fontweight='bold', fontsize=12, color='white')

# ── Chart 2: Correct vs Errors ───────────────────────────────
ax2 = fig.add_subplot(2, 2, 2)
ax2.set_facecolor('#16213e')
x, w = range(len(names)), 0.35
b1 = ax2.bar([i-w/2 for i in x], corrects, w,
             label='Correct', color='#2ecc71', edgecolor='white', linewidth=0.8, zorder=3)
b2 = ax2.bar([i+w/2 for i in x], errors, w,
             label='Errors',  color='#e74c3c', edgecolor='white', linewidth=0.8, zorder=3)
ax2.set_title('Correct vs Errors per Strategy', fontweight='bold',
              color='white', fontsize=13, pad=12)
ax2.set_ylabel('Number of Reviews', color='white')
ax2.set_xticks(list(x))
ax2.set_xticklabels(names, rotation=15, color='white')
ax2.tick_params(colors='white')
ax2.spines[['top','right','left','bottom']].set_color('#444')
ax2.grid(axis='y', alpha=0.15, zorder=0)
ax2.legend(facecolor='#1a1a2e', labelcolor='white', edgecolor='#444')
ax2.set_ylim([0, 25])
for i,(c,e) in enumerate(zip(corrects, errors)):
    ax2.text(i-w/2, c+0.3, str(c), ha='center', fontsize=11,
             fontweight='bold', color='white')
    ax2.text(i+w/2, e+0.3, str(e), ha='center', fontsize=11,
             fontweight='bold', color='white')

# ── Chart 3: Accuracy Line Trend ─────────────────────────────
ax3 = fig.add_subplot(2, 2, 3)
ax3.set_facecolor('#16213e')
ax3.plot(names, accuracies, color='#00d2ff', marker='o',
         linewidth=2.5, markersize=10, markerfacecolor='white',
         markeredgecolor='#00d2ff', markeredgewidth=2, zorder=3)
ax3.fill_between(range(len(names)), accuracies,
                 alpha=0.15, color='#00d2ff')
ax3.set_title('Accuracy Trend Across Strategies', fontweight='bold',
              color='white', fontsize=13, pad=12)
ax3.set_ylabel('Accuracy (%)', color='white')
ax3.set_ylim([0, 110])
ax3.set_xticks(range(len(names)))
ax3.set_xticklabels(names, rotation=15, color='white')
ax3.tick_params(colors='white')
ax3.spines[['top','right','left','bottom']].set_color('#444')
ax3.grid(alpha=0.15, zorder=0)
ax3.axhline(y=100, color='#2ecc71', linestyle='--', alpha=0.4)
for i,(n,a) in enumerate(zip(names, accuracies)):
    ax3.annotate(f'{a:.0f}%', (i, a),
                 textcoords="offset points", xytext=(0, 12),
                 ha='center', color='white', fontweight='bold', fontsize=11)

# ── Chart 4: Cost vs Explainability Bubble ───────────────────
ax4 = fig.add_subplot(2, 2, 4)
ax4.set_facecolor('#16213e')
cost_scores   = [5, 4, 3, 2]          # cost efficiency (higher = cheaper)
explain_scores= [1, 2, 3, 4]          # explainability (higher = more explainable)
bubble_sizes  = [a * 8 for a in accuracies]
scatter = ax4.scatter(cost_scores, explain_scores,
                      s=bubble_sizes, c=colors,
                      edgecolors='white', linewidth=1.5,
                      alpha=0.85, zorder=3)
ax4.set_title('Cost Efficiency vs Explainability\n(Bubble size = Accuracy)',
              fontweight='bold', color='white', fontsize=12, pad=12)
ax4.set_xlabel('Cost Efficiency (higher = cheaper)', color='white')
ax4.set_ylabel('Explainability (higher = more explainable)', color='white')
ax4.set_xticks([1,2,3,4,5])
ax4.set_xticklabels(['','Low','Medium','High','Very High'], color='white')
ax4.set_yticks([1,2,3,4])
ax4.set_yticklabels(['Low','Medium','Med-High','Very High'], color='white')
ax4.tick_params(colors='white')
ax4.spines[['top','right','left','bottom']].set_color('#444')
ax4.grid(alpha=0.15, zorder=0)
for i,(n,cs,es) in enumerate(zip(names, cost_scores, explain_scores)):
    ax4.annotate(n, (cs, es),
                 textcoords="offset points", xytext=(8, 5),
                 color='white', fontsize=9, fontweight='bold')

plt.tight_layout(rect=[0, 0, 1, 0.96])
plt.savefig('prompt_comparison.png', dpi=150, bbox_inches='tight',
            facecolor='#1a1a2e')
plt.show()

# ══════════════════════════════════════════════════════════════
#  STYLED DATAFRAME
# ══════════════════════════════════════════════════════════════
df_cmp = pd.DataFrame({
    'Strategy'        : ['⚡ Zero-Shot','1️⃣ One-Shot','📚 Few-Shot','🧠 Chain-of-Thought'],
    'Accuracy (%)'    : accuracies,
    'Correct / 20'    : corrects,
    'Errors'          : errors,
    'Prompt Length'   : ['Short','Medium','Long','Very Long'],
    'Reasoning'       : ['None','Minimal','Moderate','Full'],
    'Explainability'  : ['Low','Medium','Medium-High','Very High'],
    'Cost Efficiency' : ['⭐⭐⭐⭐⭐','⭐⭐⭐⭐','⭐⭐⭐','⭐⭐'],
})

def style_acc(v):
    if not isinstance(v, float): return ''
    if v >= 90:  return 'background-color:#2ecc71;color:white;font-weight:bold'
    if v >= 80:  return 'background-color:#f39c12;color:white;font-weight:bold'
    return              'background-color:#e74c3c;color:white;font-weight:bold'

def style_err(v):
    if not isinstance(v, int): return ''
    if v <= 1:  return 'background-color:#2ecc71;color:white;font-weight:bold'
    if v <= 3:  return 'background-color:#f39c12;color:white;font-weight:bold'
    return             'background-color:#e74c3c;color:white;font-weight:bold'

display(
    df_cmp.style
    .applymap(style_acc, subset=['Accuracy (%)'])
    .applymap(style_err, subset=['Errors'])
    .set_table_styles([
        {'selector': 'th', 'props': [
            ('background-color','#1a1a2e'),
            ('color','white'),
            ('font-weight','bold'),
            ('font-size','13px'),
            ('padding','10px'),
            ('border','1px solid #444')
        ]},
        {'selector': 'td', 'props': [
            ('padding','10px'),
            ('font-size','12px'),
            ('border','1px solid #ddd')
        ]},
        {'selector': 'tr:hover td', 'props': [
            ('background-color','#f0f8ff')
        ]},
        {'selector': '', 'props': [
            ('border-collapse','collapse'),
            ('width','100%')
        ]}
    ])
    .set_caption('📊 Falcon-1B Prompt Strategy Comparison — IMDB Sentiment Analysis')
    .format({'Accuracy (%)': '{:.1f}%'})
)

print("=" * 60)
print("  SAFETY & BIAS REFLECTION — IMDB DATASET")
print("=" * 60)

issues = [
    ("1. POSITIVITY BIAS",
     "Review #12 (nostalgia) wrongly labelled positive by Zero-Shot & One-Shot",
     "Positive nostalgic words ('loved','hero') misled model despite negative verdict",
     "Add nostalgic-but-negative examples to Few-Shot"),
    ("2. HTML / NOISE BIAS",
     "Raw IMDB reviews contain <br /> HTML tags",
     "Tokenizer may misinterpret HTML as content",
     "Always run clean_review() — already applied in this notebook"),
    ("3. SARCASM & IRONY BLINDNESS",
     "Mixed reviews ('amazing start, awful ending') can fool Zero-Shot",
     "Without examples, model takes surface words at face value",
     "Include ironic/sarcastic examples in Few-Shot / CoT"),
    ("4. VERBOSITY TRUNCATION BIAS",
     "Long reviews truncated to 400 chars may lose final sentiment signals",
     "FLAN-T5 token limit forces truncation of full reviews",
     "Use extractive summarisation first, or upgrade to flan-t5-large"),
    ("5. HARMFUL OUTPUT RISK",
     "Mislabelled few-shot examples systematically corrupt outputs",
     "Model treats provided labels as authoritative ground truth",
     "Audit all few-shot examples before production deployment"),
]

for name, obs, cause, fix in issues:
    print(f"\n─── {name}")
    print(f"   OBSERVED : {obs}")
    print(f"   CAUSE    : {cause}")
    print(f"   FIX      : {fix}")

print("\n─── SAFETY BEST PRACTICES")
for p in [
    "Always clean HTML/noise from text before prompting",
    "Use balanced examples (equal positive/negative) in Few-Shot",
    "Test on diverse review types: foreign, sarcasm, niche genres",
    "Apply human review before using model outputs in production",
    "Use Chain-of-Thought for high-stakes or audit-required decisions",
    "Never auto-label new training data without human audit",
    "Monitor performance drift across different review domains",
]:
    print(f"   ✅ {p}")
print("=" * 60)

# ══════════════════════════════════════════════════════════════
#  USER INPUT — CHOOSE PROMPT TYPE & RUN SENTIMENT ANALYSIS
# ══════════════════════════════════════════════════════════════

print(f'\n╔{"═"*58}╗')
print('║        INTERACTIVE PROMPT TYPE SELECTOR                 ║')
print(f'╚{"═"*58}╝')

# ── Step 1: Show available strategies ─────────────────────────
print("""
  Choose a prompting strategy:

  [1] ZERO-SHOT        — No examples, direct classification
  [2] ONE-SHOT         — One example before classifying
  [3] FEW-SHOT         — Multiple examples before classifying
  [4] CHAIN-OF-THOUGHT — Step-by-step reasoning trace
  [5] ALL              — Run all 4 strategies and compare
""")

# ── Step 2: Get strategy choice ───────────────────────────────
strategy_map = {
    "1": ("ZERO-SHOT",        zero_shot_prompt),
    "2": ("ONE-SHOT",         one_shot_prompt),
    "3": ("FEW-SHOT",         few_shot_prompt),
    "4": ("CHAIN-OF-THOUGHT", None),            # handled separately
    "5": ("ALL",              None),
}

while True:
    choice = input("📌 Enter your choice (1–5): ").strip()
    if choice in strategy_map:
        strategy_name, strategy_fn = strategy_map[choice]
        break
    print("  ⚠️  Invalid choice. Please enter a number between 1 and 5.")

print(f"\n  ✅ Selected : {strategy_name}")

# ── Step 3: Get the review ────────────────────────────────────
print("\n" + "─" * 58)
user_review = input("\n📝 Enter your movie review: ").strip()

if not user_review:
    user_review = (
        "The film had incredible visuals and a gripping soundtrack, "
        "but the story was thin and the ending made no sense at all."
    )
    print("  ⚠️  No input detected. Using default review.")

print(f'\n📝 Review  : "{user_review}"')
print(f'📏 Length  : {len(user_review)} characters')
print("─" * 58)

clean_input = clean_review(user_review)

# ══════════════════════════════════════════════════════════════
#  RUN SELECTED STRATEGY
# ══════════════════════════════════════════════════════════════

def run_single_strategy(name, fn, clean_input):
    """Runs zero/one/few-shot and prints result."""
    print(f"\n🔄 Running {name}...\n")
    prompt   = fn(clean_input)
    response = generate_response(prompt, max_new_tokens=10)
    label    = extract_label(response)
    icon     = "✅" if label == "positive" else "❌" if label == "negative" else "❓"
    print(f"  Strategy : {name}")
    print(f"  Output   : {response}")
    print(f"  {icon} Sentiment : {label.upper()}")
    return label


def run_cot_strategy(clean_input):
    """Runs CoT with step-by-step display."""
    print("\n🔄 Running CHAIN-OF-THOUGHT...\n")
    steps, label, source = run_cot(
        clean_input, generate_response, extract_label, max_new_tokens=80
    )
    icon = "✅" if label == "positive" else "❌" if label == "negative" else "❓"
    print(f"  [Reasoning via: {source}]")
    print(f"  Step 1 — Positive signals : {steps[0]}")
    print(f"  Step 2 — Negative signals : {steps[1]}")
    print(f"  Step 3 — Weighing tone    : {steps[2]}")
    print(f"  Step 4 — Final verdict    : {steps[3]}")
    print(f"\n  {icon} Sentiment : {label.upper()}")
    return label


# ── Dispatch ──────────────────────────────────────────────────
print()

if strategy_name == "ALL":
    # Run all 4 and show comparison table
    print("🔄 Running all 4 strategies...\n")
    all_strategies = [
        ("ZERO-SHOT",   zero_shot_prompt),
        ("ONE-SHOT",    one_shot_prompt),
        ("FEW-SHOT",    few_shot_prompt),
    ]
    verdicts = []

    for name, fn in all_strategies:
        print(f"─── {name}")
        lbl = run_single_strategy(name, fn, clean_input)
        verdicts.append((name, lbl))
        print()

    print("─── CHAIN-OF-THOUGHT")
    cot_lbl = run_cot_strategy(clean_input)
    verdicts.append(("CHAIN-OF-THOUGHT", cot_lbl))

    # Summary table
    print(f"\n{'=' * 58}")
    print("  COMPARISON SUMMARY")
    print(f"{'=' * 58}")
    labels = [lbl for _, lbl in verdicts]
    for name, lbl in verdicts:
        extra = " <- (with reasoning trace)" if name == "CHAIN-OF-THOUGHT" else ""
        icon  = "✅" if lbl == "positive" else "❌" if lbl == "negative" else "❓"
        print(f"  {icon} {name:<20} ->  {lbl}{extra}")

    dominant  = max(set(labels), key=labels.count)
    conf      = {4: "HIGH CONFIDENCE", 3: "LIKELY",
                 2: "MIXED / AMBIGUOUS"}.get(labels.count(dominant), "AMBIGUOUS")
    filled    = labels.count(dominant)
    bar       = '█' * filled + '░' * (4 - filled)

    print(f"\n  📊 Votes      : Positive {labels.count('positive')}/4  |  Negative {labels.count('negative')}/4")
    print(f"  📌 Confidence : {conf} — {dominant.upper()}")
    print(f"  📈 Agreement  : [{bar}] {filled}/4")

elif strategy_name == "CHAIN-OF-THOUGHT":
    run_cot_strategy(clean_input)

else:
    run_single_strategy(strategy_name, strategy_fn, clean_input)

print(f"\n{'=' * 58}")
print("  Done! Re-run this cell to try another review or strategy.")
print(f"{'=' * 58}")

"""
How it flows:
User picks [1–5]  →  User types their review
        ↓
  [1/2/3] Single strategy  →  Shows raw output + label
  [4] CoT only             →  Shows 4-step reasoning trace
  [5] ALL                  →  Runs all 4 + comparison table with vote bar
"""

"""https://bolt.new/~/sb1-owp57kbm ------ Website"""